-12
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBC
D                                   E
D  fin de partie_                   E
D                                   E
D  r recommencer le tableau         E
D  c commencer une nouvelle partie  E
D                                   E
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGH
@-04
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBC
D                                    E
D  options:                          E
D                                    E
D  +      sauvegarder votre partie   E
D  -      restaurer une sauvegarde   E
D  a      aide integree              E
D  v      visualiser les pointages   E
D  r      recommencer le tableau     E
D  c      commencer une autre partie E
D  espace pour continuer de jouer    E
D                                    E
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGH
@-04
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBC
D                                    E
D  options:                          E
D                                    E
D  c      commencer une autre partie E
D  r      restaurer une sauvegarde   E
D  a      aide integree              E
D  v      visualiser les pointages   E
D  +      recommencer le tableau     E
D  -      commencer une autre partie E
D  espace pour continuer de jouer    E
D                                    E
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGH
@-04
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBC
D pause, "espace" pour continuer. E
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGH
@-01
ABBBBBBBBBBBBBBBBBBBBBBBBBC
D                         E
D sauvegarder sous 1 - 9  E
D                         E
FGGGGGGGGGGGGGGGGGGGGGGGGGH
@-05
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBC
D                               E
D restaurer a partir de:  1 - 9 E
D                               E
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGH
@-06